apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-service
  template:
    metadata:
      labels:
        app: api-gateway-service
    spec:
      containers:
        - name: api-gateway-service
          image: your-docker-repo/api-gateway-service:latest
          ports:
            - containerPort: 8080
